import { Product } from "./types";
import i1 from "../../public/brushed-raglan-sweatshirt.webp";
import i2 from "../../public/csti.png";
import i3 from "../../public/flex-sweatshirt.webp";
import i4 from "../../public/flex-sweatpants.webp";
import i5 from "../../public/pink-fleece-sweatpants.webp";
import i6 from "../../public/lite-sweatpants.webp";
import i7 from "../../public/imperial-alpaca-hoodie.webp";
import i8 from "../../public/event3.webp";
import i9 from "../../public/muscletank.png";
import i10 from "../../public/white.png";
import i11 from "../../public/ranglan-sweatshirt.webp";
import i12 from "../../public/event2.webp";
import i13 from "../../public/i12-2.avif";
import i14 from "../../public/slimfi.webp"
import i15 from "../../public/kids.jpeg";
import i16 from "../../public/kidw.webp";
import i17 from "../../public/girl.jpeg";
import i18 from "../../public/kidg1.jpeg";
import i19 from "../../public/whitesleeveless.avif"
import i20 from "../../public/aweater.jpeg"
import i21 from "../../public/Air Jordan 1 Mid SE Craft/thumbnail.jpeg"
import i22 from "../../public/p1 Air Jordan 1 Mid SE/thumbnail.webp"
import i23 from "../../public/p2 Air Jordan XXXVII Low PF/thumbnail.webp"
import i24 from "../../public/p3 Jordan Why Not .6 PF/thumbnail.webp"
import i25 from "../../public/p4 Jordan Stay Loyal 2/thumbnail.webp"
import i26 from "../../public/p5 Jordan Delta 3 Low/thumbnail.webp"
import i27 from "../../public/p6 Air Jordan 13 Retro/thumbnail.webp"
import i28 from "../../public/p7 Air Jordan 6 Retro/thumbnail.webp"
import i29 from "../../public/p8 Air Jordan 1 Retro High OG/thumbnail.webp"
import i30 from "../../public/2022 Newest HP Envy X360.jpg";
import i31 from "../../public/ASUS Chromebook Vibe CX55 Flip, Cloud Gaming Laptop.jpg"
import i32 from "../../public/Apple iPhone 11 Pro Max.jpg";
import i33 from "../../public/Apple iPhone 12 Mini.jpg"
import i34 from "../../public/Apple iPhone 12 Pro Max.jpg";
import i35 from "../../public/Apple iPhone 8 Plus.jpg";
import i36 from "../../public/Arlo Pro 4 Spotlight Camera.jpg";
import i37 from "../../public/Arlo Ultra 2 Spotlight Camera - 2 Camera Security System.jpg";
import i38 from "../../public/Bang & Olufsen Beoplay H95 Premium Comfortable.jpg";
import i39 from "../../public/Canon EOS Rebel T7 DSLR Camera with 18-55mm Lens.jpg"
import i40 from "../../public/Fujifilm X-H2S Mirrorless Camera Body.jpg"


export const Data: Product[] = [
{
    id:1,
    title: 'Brushed Rangle Sweatshirt' ,
    type:'Sweater',
    category:"female",
    price:195,
    image:i1, 
    sale: false,
    range: 100 - 200,
    sortby: "Popular",
    rating: 5,
},
{
    id:2,
    title: 'Cameryn Sash Tie Dress' ,
    type:'Dress',
    category:"female",
    price:545,
    image:i2, 
    sale: true,
    range: 500 - 600,
    sortby: "Oldest",
    rating: 5,
},
{
    id:3,
    title: 'Flex Sweatshirt' ,
    type:'Sweater',
    category:"female",
    price:175,
    image:i3, 
    sale: true,
    range: 100 - 200,
    sortby: "MostRecent",
    rating: 5,
},
{
    id:4,
    title: 'Flex Sweatpants' ,
    type:'Pants',
    category:"female",
    price:175,
    image:i4,
    sale: false,
    range: 100 - 200,
    sortby: "Popular",
    rating: 5,
},
{
    id:5,
    title: 'Pink Fleece Sweatpants' ,
    type:'Pants', 
    category:"female",
    price:195,
    image:i5, 
    sale: false,
    range: 100 - 200,
    sortby: "MostRecent",
    rating: 5,
},
{
    id:6,
    title: 'Lite Sweatpant' ,
    type:'Pants',
    category:"female",
    price:150,
    image:i6, 
    sale: false,
    range: 100 - 200,
    sortby: "Oldest",
    rating: 5,
},
{
    id:7,
    title: 'Imperial Alpaca Hoodie' ,
    type:'Jacket',
    category:"female",
    price:525,
    image:i7, 
    sale: true,
    range: 500 - 600,
    sortby: "Popular",
    rating: 5,
},
{
    id:8,
    title: 'Flex Push Botton Bomber' ,
    type:'Jacket',
    category:"male",
    price:225,
    image:i8, 
    sale: true,
    range: 200 - 300,
    sortby: "Most Recent",
    rating: 5,
},
{
    id:9,
    title: 'Muscle Tank' ,
    type:'T shirt',
    category:"female",
    price:75,
    image:i9, 
    sale: false,
    range: 5 - 100,
    sortby: "Popular",
    rating: 5,
},
{
    id:10,
    title: 'Brushed Bomber' ,
   type:'Jacket',
   category:"female",
    price:225,
    image:i10, 
    sale: false,
    range: 200 - 300,
    sortby: "Popular",
    rating: 5,
},
{
    id:11,
    title: 'Raglan Sweatshirt' ,
    type:'Sweater',
    category:"male",
    price:195,
    image:i11, 
    sale: false,
    range: 100 - 200,
    sortby: "Oldest",
    rating: 5,
},
{
id:12,
title:"Flex Sweatshirt ",
type:'T shirt',
category:"male",
price:75,
image:i12,
sale: true,
range: 5 - 100,
sortby: "Popular",
    rating: 5,
},
{
    id:13,
    title:"Black Neck Crew T-Shirt",
    type:"T shirt",
    category:"female",
    price:120,
    image:i13,
    sale: false,
    range: 100 - 200,
    sortby: "MostRecent",
    rating: 5,
},
{
id:14,
title:"Slim Fit Pant",
type:"Pant",
category:"male",
price:250,
image:i14,
sale: false,
range: 200 - 300,
sortby: "Popular",
    rating: 5,
},
{
    id:15,
    title:"Full Sleeve Sweater",
    type:"Sweater",
    category:"kids",
    price:200,
    image:i15,
    sale: false,
    range: 100 - 200,
    sortby: "Popular",
    rating: 5,
    },
    {
        id:16,
        title:"Orange Trousers",
        type:"Trouser",
        category:"kids",
        price:190,
        image:i16,
        sale: true,
        range: 100 - 200,
        sortby: "Oldest",
    rating: 5,
        },
        {
            id:17,
            title:"Pink Full Sleeve Sweater",
            type:"Sweater",
            category:"kids",
            price:210,
            image:i17,
            sale: true,
            range: 200 - 300,
            sortby: "Popular",
            rating: 5,
            },
            {
                id:18,
                title:"Grey Full Sleeve Shirt",
                type:"Shirt",
                category:"kids",
                price:180,
                image:i18,
                sale: false,
                range: 100 - 200,
                sortby: "Popular",
    rating: 5,
                },
                
                
                {
                    id:19,
                    title:"White Sleeveless Shirt",
                    type:"Shirt",
                    category:"female",
                    price:240,
                    image:i19,
                    sale: true,
                    range: 200 - 300,
                    sortby: "Popular",
    rating: 5,
                    },

{
    id:20,
    title:"Brown Fullsleeve Sweater",
    type:"Sweater",
    category:"female",
    price: 255,
    image:i20,
    sale: false,
    range: 200 - 300,
    sortby: "Oldest",
    rating: 5,
    },
    {
        id:21,
        title: 'Air Jordan 1 Mid SE Craft' ,
        type:'Shoe',
        category:"Shoe",
        price:195,
        image:i21, 
        sale: true,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:22,
        title: 'p1 Air Jordan 1 Mid SE' ,
        type:'Shoe',
        category:"Shoe",
        price:120,
        image:i22, 
        sale: false,
        range: 100 - 200,
        sortby: "Popular",
        rating: 5,
    },
    {
        id:23,
        title: 'p2 Air Jordan XXXVII Low PF' ,
        type:'Shoe',
        category:"Shoe",
        price:195,
        image:i23, 
        sale: true,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:24,
        title: 'p3 Jordan Why Not .6 PF' ,
        type:'Shoe',
        category:"Shoe",
        price:200,
        image:i24, 
        sale: false,
        range: 100 - 200,
        sortby: "Oldest",
    rating: 5,
    },
    {
        id:24,
        title: 'p4 Jordan Stay Loyal 2' ,
        type:'Sweater',
        category:"Shoe",
        price:195,
        image:i25, 
        sale: true,
        range: 100 - 200,
        sortby: "MostRecent",
    rating: 5,
    },
    {
        id:25,
        title: 'p5 Jordan Delta 3 Low' ,
        type:'Shoe',
        category:"Shoe",
        price:250,
        image:i26, 
        sale: false,
        range: 200 - 300,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:26,
        title: 'p6 Air Jordan 13 Retro' ,
        type:'Shoe',
        category:"Shoe",
        price:195,
        image:i27, 
        sale: true,
        range: 100 - 200,
        sortby: "Oldest",
    rating: 5,
    },
    {
        id:27,
        title: 'p7 Air Jordan 6 Retro' ,
        type:'Shoe',
        category:"Shoe",
        price:200,
        image:i28, 
        sale: false,
        range: 100 - 200,
        sortby: "MostRecent",
    rating: 5,
    },
    {
        id:28,
        title: 'p8 Air Jordan 1 Retro High OG' ,
        type:'Shoe',
        category:"Shoe",
        price:175,
        image:i29, 
        sale: true,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:30,
        title: '2022 Newest HP Envy X360' ,
        type:'Electronic',
        category:"Electronic",
        price:175,
        image:i30, 
        sale: false,
        range: 100 - 200,
        sortby: "MostRecent",
    rating: 5,
    },
    {
        id:31,
        title: 'ASUS Chromebook Vibe CX55 Flip, Cloud Gaming Laptop' ,
        type:'Electronic',
        category:"Electronic",
        price:175,
        image:i31, 
        sale: true,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:32,
        title: 'Apple iPhone 11 Pro Max' ,
        type:'Electronic',
        category:"Electronic",
        price:175,
        image:i32, 
        sale: true,
        range: 100 - 200,
        sortby: "MostRecent",
    rating: 5,
    },
    {
        id:33,
        title: 'Apple iPhone 12 Mini' ,
        type:'Electronic',
        category:"Electronic",
        price:175,
        image:i33, 
        sale: true,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:34,
        title: 'Apple iPhone 12 Pro Max' ,
        type:'Electronic',
        category:"Electronic",
        price:122,
        image:i34, 
        sale: false,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:35,
        title: 'Apple iPhone 8 Plus' ,
        type:'Electronic',
        category:"Electronic",
        price:175,
        image:i35, 
        sale: false,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:36,
        title: 'Arlo Pro 4 Spotlight Camera' ,
        type:'Electronic',
        category:"Electronic",
        price:635,
        image:i36, 
        sale: true,
        range: 600 - 700,
        sortby: "Oldest",
    rating: 5,
    },
    {
        id:37,
        title: 'Arlo Ultra 2 Spotlight Camera - 2 Camera Security System' ,
        type:'Electronic',
        category:"Electronic",
        price:175,
        image:i37, 
        sale: true,
        range: 100 - 200,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:38,
        title: 'Bang & Olufsen Beoplay H95 Premium Comfortable' ,
        type:'Electronic',
        category:"Electronic",
        price:250,
        image:i38, 
        sale: true,
        range: 200 - 300,
        sortby: "Popular",
    rating: 5,
    },
    {
        id:39,
        title: 'Canon EOS Rebel T7 DSLR Camera with 18-55mm Lens' ,
        type:'Electronic',
        category:"Electronic",
        price:342,
        image:i39, 
        sale: false,
        range: 300 - 400,
        sortby: "MostRecent",
    rating: 5,
    },
    {
        id:40,
        title: 'public/Fujifilm X-H2S Mirrorless Camera Body' ,
        type:'Electronic',
        category:"Electronic",
        price:525,
        image:i40, 
        sale: true,
        range: 500 - 600,
        sortby: "Popular",
    rating: 5,
    }
];